## 客户端报错
```
2024-09-18 12:01:17,933 ...正常的业务日志...

// 这里查统计库报错，可以看到这里已经过了8个小时
2024-09-18 20:01:27,645 org.springframework.dao.RecoverableDataAccessException: 
    ### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: 
    The last packet successfully received from the server was 28,825,297 milliseconds ago.  
    The last packet sent successfully to the server was 28,809,701 milliseconds ago. is longer than the server configured value of 'wait_timeout'. 
    You should consider either expiring and/or testing connection validity before use in your application, 
    increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

// 这里查业务库报错
2024-09-18 20:01:27,655 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:211] [WARN NewPooledConnection] - 
    [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
2024-09-18 20:01:27,656 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:214] [WARN NewPooledConnection] - 
    [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 28,809,722 milliseconds ago.  
    The last packet sent successfully to the server was 28,809,722 milliseconds ago. is longer than the server configured value of 'wait_timeout'. 
    You should consider either expiring and/or testing connection validity before use in your application, 
    increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. ] which will not be reported to listeners!

// 这里查业务库报错
2024-09-18 20:01:27,658 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:211] [WARN NewPooledConnection] - 
    [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
2024-09-18 20:01:27,659 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:214] [WARN NewPooledConnection] - 
    [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 28,809,725 milliseconds ago. 
    The last packet sent successfully to the server was 28,809,725 milliseconds ago. is longer than the server configured value of 'wait_timeout'. 
    You should consider either expiring and/or testing connection validity before use in your application, 
    increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. ] which will not be reported to listeners!

// 这里查业务库报错
2024-09-18 20:01:27,663 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:211] [WARN NewPooledConnection] - 
    [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
2024-09-18 20:01:27,664 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:214] [WARN NewPooledConnection] - 
    [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 28,809,730 milliseconds ago.  
    The last packet sent successfully to the server was 28,809,730 milliseconds ago. is longer than the server configured value of 'wait_timeout'. 
    You should consider either expiring and/or testing connection validity before use in your application, 
    increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. ] which will not be reported to listeners!

// 这里是事务提交报错
2024-09-18 20:01:27,671 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:211] [WARN NewPooledConnection] - 
    [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
2024-09-18 20:01:27,671 [5143734671173152768][Dispatch-Service-thread-25629] [Slf4jMLog.java:214] [WARN NewPooledConnection] - 
    [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). 
    Transaction resolution unknown. ] which will not be reported to listeners!
    com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.
```

## 问题分析
#### MySQL服务器配置的wait_timeout是8小时
```
SHOW VARIABLES LIKE 'wait_timeout';
28800
```

#### C3P0每60秒检查一次连接，使用前后均不检查连接有效性
```
<property name="checkPeriod" value="60" />
<property name="checkSql" value="select 1 from dual" />
```

#### 原因猜测
- 60秒检查的时候连接是有效的，但是在下一轮检查前：
  - MySQL服务端（或代理端）强制关闭连接。
  - 程序获取已失效的连接并执行查询。
    - 虽然失效，但是获取前没有检查连接有效性，所以继续使用
    - 程序没有指定超时时间，所以使用默认的8小时

#### 进一步思考
- 开启获取连接检查有效果么？针对这种场景应该是无效的，应该这个检查实际上也是查数据库，也是会超时8小时的。
- 更好的方式应该是程序默认一个较短的超时时间，比如3秒钟。然后特殊场景再配置长一点。